### ISSUE TITLE
Evaluation set on relight task

### ISSUE THREAD

**Issue by pureexe** [renjiaoyi/imagerelighting#2]
Thank you for the great work on image relighting.

However, as the paper section 6.2 said that 

> "For quantitative evaluations, we rendered an evaluation set of 100 objects under 30 lighting environments, with various materials"

Is it possible to provide the set of **100 objects**, **30 lighting environments** and/or **rendered image**?

**Comment by renjiaoyi** [comment]
Hi there,

Thanks for your interest in our work. 

Here we have the normal maps and masks of objects, HDR files, and precomputed SH coefficients. With them, you can render the relit images and adjust the glossiness parameter with these files.  

I also provide our rendering (diffuse and specular renderings with glossiness as 5 and 15) for reference. 

The link is https://www.jianguoyun.com/p/DTyRMCoQ79HXBxia6JQFIAA

**Comment by pureexe** [comment]
Thank you for sharing!

However, I cannot download the pre-rendered image. (`3_renders_diff_sh`, `3_renders_spec_5`, `3_renders_spec_15`) the website mention there are too many files. Could you make a zip file that contains the image instead?

![image](https://github.com/renjiaoyi/imagerelighting/assets/1303847/f496d9ab-a1b2-4e71-80fc-1f55f7d39708)

**Comment by renjiaoyi** [comment]
I uploaded zip files, please check again.

**Comment by pureexe** [comment]
> I uploaded zip files, please check again.

Thank you so much, Now I can download the file.
